name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      if: github.event_name == 'issues'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: antzyyy123

    - name: 'Auto-assign pull request'
      if: github.event_name == 'pull_request'
      uses: toshimaru/auto-author-assign@v2.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
